USE SqlMasterClass;

SET FOREIGN_KEY_CHECKS = 0;

DROP TRIGGER IF EXISTS trigger_validate_score;
DROP TRIGGER IF EXISTS trigger_log_problem_creation;
DROP TRIGGER IF EXISTS trigger_update_leaderboard;

DROP PROCEDURE IF EXISTS archive_old_submissions;

DROP FUNCTION IF EXISTS calculate_acceptance_rate;

DROP VIEW IF EXISTS ActiveProblemsWithStats;

DROP TABLE IF EXISTS CodeCell;
DROP TABLE IF EXISTS TranscriptMessage;
DROP TABLE IF EXISTS Embedding;
DROP TABLE IF EXISTS AutograderLog;
DROP TABLE IF EXISTS Submission;
DROP TABLE IF EXISTS Reference;
DROP TABLE IF EXISTS ProblemTag;
DROP TABLE IF EXISTS FlaggedContent;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Assigns;
DROP TABLE IF EXISTS Problem;
DROP TABLE IF EXISTS DatasetVersion;
DROP TABLE IF EXISTS Dataset;
DROP TABLE IF EXISTS Resource;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS InterviewSession;
DROP TABLE IF EXISTS LeaderboardEntry;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS Submission_Archive;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Logs;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS ProblemStatement;
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Scores;
DROP TABLE IF EXISTS Transactions;


SET FOREIGN_KEY_CHECKS = 1;

DROP SCHEMA IF EXISTS SqlMasterClass;