USE FairwayRateHub;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CachedQuestion;
DROP TABLE IF EXISTS QuestionLog;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS GolfCourse;
DROP TABLE IF EXISTS `User`;

SET FOREIGN_KEY_CHECKS = 1;

DROP SCHEMA IF EXISTS FairwayRateHub;
